version: '3.8'

services:

  postgres:
    image: postgres
    container_name: gymspacedb
    restart: always
    environment:
      POSTGRES_DB: gymspace
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: gymspacecaching
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: